### PR TITLE
Added Groups for Notification Service

### PR DESCRIPTION
**Pull request by komakkar**
The following are added to UserInfo and TenantInfo. 
1. Pubsub
2. Ops
3. Cron

## All Submissions:
-------------------------------------
* [YES/NO] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES/NO] I have updated the documentation accordingly.
* [YES/NO/NA] I have added tests to cover my changes.
* [YES/NO/NA] All new and existing tests passed.
* [YES/NO/NA] I have formatted the terraform code.  _(`terraform fmt -recursive && go fmt ./...`)_

## Current Behavior or Linked Issues
-------------------------------------

https://github.com/Azure/osdu-infrastructure/issues/197

## Does this introduce a breaking change?
-------------------------------------
- [YES/NO]

## Other information
-------------------------------------

### CODE REVIEW

**Comment by danielscholl** [comment]
Can you rebase in the changes that already exist to resolve the conflicts?

**Review by danielscholl — CHANGES_REQUESTED** [review]
Needs an Issue in Gitlab and then determine the proper place for the changes.

**Comment by komakkar** [comment]
> Needs an Issue in Gitlab and then determine the proper place for the changes.

I created an issue in github itself. I will make the issue in Gitlab and close the github ones.

**Comment by komakkar** [comment]
As the repo is migrating to Gitlab, moved the changes to Gitlab

**Pull request closed without merging**
