### PR TITLE
Changed the creation order of data and services resources

### PR DESCRIPTION
**Pull request by vasyl-leskiv**
## All Submissions:
-------------------------------------
* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES] I have updated the documentation accordingly.
* [NO] I have added tests to cover my changes.
* [YES] All new and existing tests passed.
* [YES] I have formatted the terraform code.  _(`terraform fmt -recursive && go fmt ./...`)_

## Current Behavior or Linked Issues
-------------------------------------
Issue #103 

## Does this introduce a breaking change?
-------------------------------------
- Have not yet checked if the setup needs to be recreated.

## Other information
-------------------------------------
As role assignments creation was moved from service_resources pipeline to data_resources pipeline, we might want to configure integration tests with the way to check if these roles exist in data_resources

### CODE REVIEW

**Comment by vasyl-leskiv** [comment]
@danielscholl ,
Can you please take a look at this PR?

**Comment by danielscholl** [comment]
This appears to have been a breaking change.  For now I've pulled this into an isolated branch `datapartition` in order to dive deeper into what might have caused the environment to break.

**Comment by vasyl-leskiv** [comment]
> This appears to have been a breaking change. For now I've pulled this into an isolated branch `datapartition` in order to dive deeper into what might have caused the environment to break.

@danielscholl 
There is a chance you would need to resetup current resource groups since these changes support the new order of the RG creation.

**Comment by danielscholl** [comment]
This PR is now being handled in an alternate manner and being tracked Under a Project.  https://github.com/Azure/osdu-infrastructure/projects/4

**Pull request closed without merging**
