### PR TITLE
Adding new Resources for WKS and Schema services

### PR DESCRIPTION
**Pull request by harshit283**
## All Submissions:
-------------------------------------
* [YES/NO] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES/NO] I have updated the documentation accordingly.
* [YES/NO/NA] I have added tests to cover my changes.
* [YES/NO/NA] All new and existing tests passed.
* [YES/NO/NA] I have formatted the terrafrom code.  _(`terraform fmt -recursive && go fmt ./...`)_

## Current Behavior or Linked Issues
-------------------------------------

## Does this introduce a breaking change?
-------------------------------------
- [YES/NO]

## Other information
-------------------------------------
Added new resources required for WKS and schema services
Resources added 
1. 4 Cosmos Db containers -> Authority, EntityType, SchemaInfo, Source
2. 1 Storage container -> osdu-wks-mappings
3. 1 service bus subscription -> wkssubscription on recordstopic

### CODE REVIEW

**Comment by harshit283** [comment]
@danielscholl @polavishnu4444

**Review by polavishnu4444 — APPROVED** [review]
LGTM

**Comment by imran-siddique** [comment]
@polavishnu4444 - Can this be closed?

**Comment by danielscholl** [comment]
Closing this issue as all these things are now added into the osdu-mvp architecture.

**Pull request merged**
